  
metadata:
  name: remote-service-name
  annotations:
    io.cilium/global-service: "true"
    io.cilium/shared-service: "false"

spec:
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: ClusterIP