apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "csi-driver-nfs-pvc.fullname" . }}
  labels:
    {{- include "csi-driver-nfs-pvc.labels" . | nindent 4 }}
spec:
  capacity:
    {{- toYaml .Values.pv.capacity | nindent 4 }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  csi:
    readOnly: false
    volumeHandle: {{ include "csi-driver-nfs-pvc.fullname" . }}
    {{- toYaml .Values.csi | nindent 4 }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "csi-driver-nfs-pvc.fullname" . }}
  labels:
    {{- include "csi-driver-nfs-pvc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    {{- toYaml .Values.pvc.resources | nindent 4 }}
  volumeName:  {{ include "csi-driver-nfs-pvc.fullname" . }}
  storageClassName: ""
