{{- if .Values.pv.enable -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "csi-driver-nfs-pvc.fullname" . }}
  labels:
    {{- include "csi-driver-nfs-pvc.labels" . | nindent 4 }}
spec:
  capacity:
    {{- toYaml .Values.pv.capacity | nindent 4 }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  csi:
    readOnly: false
    volumeHandle: {{ include "csi-driver-nfs-pvc.fullname" . }}
    {{- toYaml .Values.csi | nindent 4 }}
{{- end -}}
{{- if .Values.pvc.enable }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "csi-driver-nfs-pvc.fullname" . }}
  labels:
    {{- include "csi-driver-nfs-pvc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    {{- toYaml .Values.pvc.resources | nindent 4 }}
  volumeName:  {{ include "csi-driver-nfs-pvc.fullname" . }}
  storageClassName: ""
{{- end -}}
{{- if .Values.storageClass.enable }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "csi-driver-nfs-pvc.labels" . | nindent 4 }}
parameters:
  {{- toYaml .Values.csi.volumeAttributes | nindent 2 }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
{{- end -}}
